services:
  coffee-order-database:
    image: postgres:alpine
    container_name: coffee-order-database
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coffee
